/**
 * @fileoverview gRPC-Web generated client stub for testF1Api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: testF1.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.testF1Api = require('./testF1_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.testF1Api.TestF1ProtoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.testF1Api.TestF1ProtoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.CreateUserRequest,
 *   !proto.testF1Api.CreateUserResponse>}
 */
const methodDescriptor_TestF1ProtoService_CreateUser = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.CreateUserRequest,
  proto.testF1Api.CreateUserResponse,
  /**
   * @param {!proto.testF1Api.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.CreateUserResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.CreateUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.CreateUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_CreateUser,
      callback);
};


/**
 * @param {!proto.testF1Api.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.CreateUserResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.LoginRequest,
 *   !proto.testF1Api.LoginResponse>}
 */
const methodDescriptor_TestF1ProtoService_Login = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/Login',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.LoginRequest,
  proto.testF1Api.LoginResponse,
  /**
   * @param {!proto.testF1Api.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/Login',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_Login,
      callback);
};


/**
 * @param {!proto.testF1Api.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/Login',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.EmptyRequest,
 *   !proto.testF1Api.ListCouncilResponse>}
 */
const methodDescriptor_TestF1ProtoService_ListCouncils = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/ListCouncils',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.EmptyRequest,
  proto.testF1Api.ListCouncilResponse,
  /**
   * @param {!proto.testF1Api.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.ListCouncilResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.ListCouncilResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.ListCouncilResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.listCouncils =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListCouncils',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListCouncils,
      callback);
};


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.ListCouncilResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.listCouncils =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListCouncils',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListCouncils);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.EmptyRequest,
 *   !proto.testF1Api.ListBasicInformationResponse>}
 */
const methodDescriptor_TestF1ProtoService_ListBasicInformation = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/ListBasicInformation',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.EmptyRequest,
  proto.testF1Api.ListBasicInformationResponse,
  /**
   * @param {!proto.testF1Api.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.ListBasicInformationResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.ListBasicInformationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.ListBasicInformationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.listBasicInformation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListBasicInformation',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListBasicInformation,
      callback);
};


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.ListBasicInformationResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.listBasicInformation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListBasicInformation',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListBasicInformation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.AddCouncilRequest,
 *   !proto.testF1Api.AddCouncilResponse>}
 */
const methodDescriptor_TestF1ProtoService_AddCouncil = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/AddCouncil',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.AddCouncilRequest,
  proto.testF1Api.AddCouncilResponse,
  /**
   * @param {!proto.testF1Api.AddCouncilRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.AddCouncilResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.AddCouncilRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.AddCouncilResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.AddCouncilResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.addCouncil =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/AddCouncil',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_AddCouncil,
      callback);
};


/**
 * @param {!proto.testF1Api.AddCouncilRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.AddCouncilResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.addCouncil =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/AddCouncil',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_AddCouncil);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.DeleteCouncilRequest,
 *   !proto.testF1Api.Response>}
 */
const methodDescriptor_TestF1ProtoService_DeleteCouncil = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/DeleteCouncil',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.DeleteCouncilRequest,
  proto.testF1Api.Response,
  /**
   * @param {!proto.testF1Api.DeleteCouncilRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.Response.deserializeBinary
);


/**
 * @param {!proto.testF1Api.DeleteCouncilRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.deleteCouncil =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/DeleteCouncil',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_DeleteCouncil,
      callback);
};


/**
 * @param {!proto.testF1Api.DeleteCouncilRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.Response>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.deleteCouncil =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/DeleteCouncil',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_DeleteCouncil);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.GetFullUserInfoRequest,
 *   !proto.testF1Api.GetFullUserInfoResponse>}
 */
const methodDescriptor_TestF1ProtoService_GetFullUserInfo = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/GetFullUserInfo',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.GetFullUserInfoRequest,
  proto.testF1Api.GetFullUserInfoResponse,
  /**
   * @param {!proto.testF1Api.GetFullUserInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.GetFullUserInfoResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.GetFullUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.GetFullUserInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.GetFullUserInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.getFullUserInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/GetFullUserInfo',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_GetFullUserInfo,
      callback);
};


/**
 * @param {!proto.testF1Api.GetFullUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.GetFullUserInfoResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.getFullUserInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/GetFullUserInfo',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_GetFullUserInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.DeleteUserRequest,
 *   !proto.testF1Api.Response>}
 */
const methodDescriptor_TestF1ProtoService_DeleteUser = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/DeleteUser',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.DeleteUserRequest,
  proto.testF1Api.Response,
  /**
   * @param {!proto.testF1Api.DeleteUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.Response.deserializeBinary
);


/**
 * @param {!proto.testF1Api.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.deleteUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_DeleteUser,
      callback);
};


/**
 * @param {!proto.testF1Api.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.Response>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.deleteUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_DeleteUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.GetRegistryRequest,
 *   !proto.testF1Api.GetRegistryResponse>}
 */
const methodDescriptor_TestF1ProtoService_GetRegistry = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/GetRegistry',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.GetRegistryRequest,
  proto.testF1Api.GetRegistryResponse,
  /**
   * @param {!proto.testF1Api.GetRegistryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.GetRegistryResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.GetRegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.GetRegistryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.GetRegistryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.getRegistry =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/GetRegistry',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_GetRegistry,
      callback);
};


/**
 * @param {!proto.testF1Api.GetRegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.GetRegistryResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.getRegistry =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/GetRegistry',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_GetRegistry);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testF1Api.EmptyRequest,
 *   !proto.testF1Api.ListProfessionsResponse>}
 */
const methodDescriptor_TestF1ProtoService_ListProfessions = new grpc.web.MethodDescriptor(
  '/testF1Api.TestF1ProtoService/ListProfessions',
  grpc.web.MethodType.UNARY,
  proto.testF1Api.EmptyRequest,
  proto.testF1Api.ListProfessionsResponse,
  /**
   * @param {!proto.testF1Api.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testF1Api.ListProfessionsResponse.deserializeBinary
);


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testF1Api.ListProfessionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testF1Api.ListProfessionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testF1Api.TestF1ProtoServiceClient.prototype.listProfessions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListProfessions',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListProfessions,
      callback);
};


/**
 * @param {!proto.testF1Api.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testF1Api.ListProfessionsResponse>}
 *     Promise that resolves to the response
 */
proto.testF1Api.TestF1ProtoServicePromiseClient.prototype.listProfessions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testF1Api.TestF1ProtoService/ListProfessions',
      request,
      metadata || {},
      methodDescriptor_TestF1ProtoService_ListProfessions);
};


module.exports = proto.testF1Api;

